name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm i

      - name: Build Next.js project
        run: ./Makerelease

      - name: Compress files
        run: tar -czvf Site.tar.gz .next/standalone
        
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "Site.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call POST request
        run: |
            curl -X POST -H "Content-Type: application/json" -d '{"tag": "${{ github.ref }}", "token": '"$BUILD_TOKEN"'}' https://gpt-prompt-test-ten.vercel.app/api/update_template
